<!DOCTYPE html>
<!--[if IE 8]><html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  
  
  <title>Exceptions - CS14 SI: Spring 2015</title>
  

  <link rel="shortcut icon" href="../img/favicon.ico">

  
  <link href='https://fonts.googleapis.com/css?family=Lato:400,700|Roboto+Slab:400,700|Inconsolata:400,700' rel='stylesheet' type='text/css'>

  <link rel="stylesheet" href="../css/theme.css" type="text/css" />
  <link rel="stylesheet" href="../css/theme_extra.css" type="text/css" />
  <link rel="stylesheet" href="../css/highlight.css">

  
  <script>
    // Current page data
    var mkdocs_page_name = "Exceptions";
    var mkdocs_page_input_path = "lec_week_03_pt2.md";
    var mkdocs_page_url = "/lec_week_03_pt2/";
  </script>
  
  <script src="../js/jquery-2.1.1.min.js"></script>
  <script src="../js/modernizr-2.8.3.min.js"></script>
  <script type="text/javascript" src="../js/highlight.pack.js"></script>
  <script src="../js/theme.js"></script> 

  
</head>

<body class="wy-body-for-nav" role="document">

  <div class="wy-grid-for-nav">

    
    <nav data-toggle="wy-nav-shift" class="wy-nav-side stickynav">
      <div class="wy-side-nav-search">
        <a href=".." class="icon icon-home"> CS14 SI: Spring 2015</a>
        <div role="search">
  <form id ="rtd-search-form" class="wy-form" action="../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
  </form>
</div>
      </div>

      <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">
        <ul class="current">
          
            <li>
    <li class="toctree-l1 ">
        <a class="" href="..">Home</a>
        
    </li>
<li>
          
            <li>
    <li class="toctree-l1 ">
        <a class="" href="../lec_week_02/">Lecture Week 2</a>
        
    </li>
<li>
          
            <li>
    <li class="toctree-l1 ">
        <a class="" href="../lab_week_02/">Lab Week 2</a>
        
    </li>
<li>
          
            <li>
    <ul class="subnav">
    <li><span>Lecture Week 3</span></li>

        
            
    <li class="toctree-l1 ">
        <a class="" href="../lec_week_03/">Stacks & Queues</a>
        
    </li>

        
            
    <li class="toctree-l1 current">
        <a class="current" href="./">Exceptions</a>
        
            <ul>
            
                <li class="toctree-l3"><a href="#exceptions">Exceptions</a></li>
                
                    <li><a class="toctree-l4" href="#exceptions-with-functions">Exceptions with functions</a></li>
                
                    <li><a class="toctree-l4" href="#multiple-exceptions">Multiple Exceptions</a></li>
                
            
            </ul>
        
    </li>

        
            
    <li class="toctree-l1 ">
        <a class="" href="../lec_week_03_pt3/">Templates</a>
        
    </li>

        
    </ul>
<li>
          
            <li>
    <li class="toctree-l1 ">
        <a class="" href="../lab_week_03/">Lab Week 3</a>
        
    </li>
<li>
          
            <li>
    <li class="toctree-l1 ">
        <a class="" href="../lab_week_04/">Lab Week 4</a>
        
    </li>
<li>
          
            <li>
    <li class="toctree-l1 ">
        <a class="" href="../lec_week_04/">Lecture Week 4</a>
        
    </li>
<li>
          
        </ul>
      </div>
      &nbsp;
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">

      
      <nav class="wy-nav-top" role="navigation" aria-label="top navigation">
        <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
        <a href="..">CS14 SI: Spring 2015</a>
      </nav>

      
      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="breadcrumbs navigation">
  <ul class="wy-breadcrumbs">
    <li><a href="..">Docs</a> &raquo;</li>
    
      
        
          <li>Lecture Week 3 &raquo;</li>
        
      
    
    <li>Exceptions</li>
    <li class="wy-breadcrumbs-aside">
      
    </li>
  </ul>
  <hr/>
</div>
          <div role="main">
            <div class="section">
              
                <h1 id="exceptions">Exceptions</h1>
<p>An <strong>exception</strong> is a circumstance that a program was not designed to handle. They are useful for when you need your program to detect and handle errors that may occur during program execution.</p>
<p>Here's an example of code without error checking:</p>
<pre><code class="cpp">#include &lt;iostream&gt;
using namespace std;

int main()
{
  //Get height input
  int height = 0;
  cout &lt;&lt; &quot;Enter your height (in inches): &quot;;
  cin &gt;&gt; height;

  //Return converted height input
  int feet = height / 12;
  int inches = height % 12;
  cout &lt;&lt; &quot;Your height is equivalant to: &quot; &lt;&lt; feet &lt;&lt; &quot; feet &quot; &lt;&lt; inches &lt;&lt; &quot; inches!&quot; &lt;&lt; endl;

  return 0;
}
</code></pre>

<p>Now let's do some test with some edge cases and see what the program outputs:</p>
<pre><code class="cpp">//Normal Input
Enter your height (in inches): 75
Your height is equivalant to: 6 feet 3 inches!

//Zero Input
Enter your height (in inches): 0
Your height is equivalant to: 0 feet 0 inches!

//Negative Input
Enter your height (in inches): -54
Your height is equivalant to: -4 feet -6 inches!    //&lt;------- Oh no!
</code></pre>

<p>So what most of you have been doing to avoid this error is a good implementation of branches!</p>
<pre><code class="cpp">#include &lt;iostream&gt;
using namespace std;

int main()
{
  //Get height input
  int height = 0;
  cout &lt;&lt; &quot;Enter your height (in inches): &quot;;
  cin &gt;&gt; height;

  //If the height is less than 0, output error message and return
  if(height &lt; 0)
  {
    cout &lt;&lt; &quot;Error! Invalid height!&quot; &lt;&lt; endl;
    return 0;
  }

  //Return converted height input
  int feet = height / 12;
  int inches = height % 12;
  cout &lt;&lt; &quot;Your height is equivalant to: &quot; &lt;&lt; feet &lt;&lt; &quot; feet &quot; &lt;&lt; inches &lt;&lt; &quot; inches!&quot; &lt;&lt; endl;

  return 0;
}
</code></pre>

<p>Now let's test this new code with the same input:</p>
<pre><code class="cpp">//Normal Input
Enter your height (in inches): 75
Your height is equivalant to: 6 feet 3 inches!

//Zero Input
Enter your height (in inches): 0
Your height is equivalant to: 0 feet 0 inches!

//Negative Input
Enter your height (in inches): -54
Error! Invalid height!                //&lt;----- Much better~
</code></pre>

<p>A more sophisticated way of handling these errors are <strong>exception-handling constructs</strong>. Using these constructs allows us to keep error-checking code separate from our main code.</p>
<pre><code class="cpp">//Exception handling construct

//... means normal code
//...
try
{
  //...

  //If error detected
  throw objectOfExceptionType;

  //...

}
catch (exceptionType execptionObject)
{
  //Handle exception, e.g., print message
}
//...
</code></pre>

<p>Exception constructs have three parts:</p>
<ul>
<li>A <code>try</code> block surrounds normal code, which is exited immediately if a throw statement executes.</li>
<li>A <code>throw</code> statement appears within a try block; if reached, execution jumps immediately to the end of the try block. The code is written so only error situations lead to reaching a throw. The throw statement provides an object of a particular type, such as an object of type "runtime_error", which is a class defined in the <strong>stdexcept</strong> library. The statement is said to throw an exception of the particular type. A throw statement's syntax is similar to a return statement.</li>
<li>A <code>catch</code> clause immediately follows a try block; if the catch was reached due to an exception thrown of the catch clause's parameter type, the clause executes. The clause is said to catch the thrown exception. A catch block is called a <strong>handler</strong> because it handles an exception.</li>
</ul>
<p>Here's the earlier program using exception-handling constructs. Notice that the normal code flow is not obscured by error-checking/handling if-else statements.</p>
<pre><code class="cpp">#include &lt;iostream&gt;
#include &lt;stdexcept&gt;  //Exception class
using namespace std;

int main()
{
  //Get height input
  int height = 0;

  try
  {
    //Get input
    cout &lt;&lt; &quot;Enter your height (in inches): &quot;;
    cin &gt;&gt; height;

    if(height &lt; 0)
    {
      throw runtime_error(&quot;Error! Invalid height!&quot;);
    }

    //Return converted height input
    int feet = height / 12;
    int inches = height % 12;
    cout &lt;&lt; &quot;Your height is equivalant to: &quot; &lt;&lt; feet &lt;&lt; &quot; feet &quot; &lt;&lt; inches &lt;&lt; &quot; inches!&quot; &lt;&lt; endl;
  }
  catch(runtime_error &amp;excpt)
  {
    //Print error message passed by throw statement
    cout &lt;&lt; excpt.what() &lt;&lt; endl;
  }

  return 0;
}
</code></pre>

<pre><code class="cpp">Output:
//Normal Input
Enter your height (in inches): 75
Your height is equivalant to: 6 feet 3 inches!

//Zero Input
Enter your height (in inches): 0
Your height is equivalant to: 0 feet 0 inches!

//Negative Input
Enter your height (in inches): -54
Error! Invalid height!              

</code></pre>

<h2 id="exceptions-with-functions">Exceptions with functions</h2>
<p>Now you may be thinking, why even use exceptions?</p>
<p><img alt="alt text" src="http://i.imgur.com/A62vCJ8.jpg?fb" /></p>
<p>Well, the power of exceptions becomes clearer when used within a function. If an exception is thrown within a function and not caught within that function, then the function is immediately exited and the calling function is checked for a handler, and so on up the function call hierarchy.</p>
<p>Here's an expanded program where we utilize functions with execptions:</p>
<pre><code class="cpp">#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
using namespace std;

void getHeight(int &amp; feet, int &amp; inches)
{
   int height = 0; // User defined weight

   // Get user data
   cout &lt;&lt; &quot;Enter height (in inches): &quot;;
   cin &gt;&gt; height;

   // Error checking, non-negative weight
   if (height &lt; 0)
   {
      throw runtime_error(&quot;Error! Invalid height!&quot;);
   }

   //Calculate conversions
   feet = height / 12;
   inches = height % 12;

   return;
}

void getWeight(double &amp; kilograms)
{
  int weight; // User defined weight

  //Get user Data
  cout &lt;&lt; &quot;Enter weight (in pounds): &quot;;
  cin &gt;&gt; weight;

  if (weight &lt; 0)
  {
      throw runtime_error(&quot;Error! Invalid weight!&quot;);
  }

  //Calculate conversions
  kilograms = weight / 0.453592;

  return;
}

int main()
{
  int feet, inches = 0;
  double kilograms = 0;

  try
  {
      //Get user data
      getHeight(feet, inches);
      getWeight(kilograms);

      cout &lt;&lt; &quot;Your height is equivalant to: &quot; &lt;&lt; feet &lt;&lt; &quot; feet &quot; &lt;&lt; inches &lt;&lt; &quot; inches!&quot; &lt;&lt; endl
           &lt;&lt; &quot;Your weight is equivalant to: &quot; &lt;&lt; kilograms &lt;&lt; &quot; kilograms!&quot; &lt;&lt; endl;
  }
  catch (runtime_error &amp; excpt)
  {
      cout &lt;&lt; excpt.what() &lt;&lt; endl;
      cout &lt;&lt; &quot;Cannot compute info.&quot; &lt;&lt; endl;
  }

  return 0;
}
</code></pre>

<p>In the code above we added a part to take in the user's weight. We then separated the user input into two different functions, each throwing their own exception. Now let's look at the code output:</p>
<pre><code class="cpp">//Valid input
Enter height (in inches): 75
Enter weight (in pounds): 150
Your height is equivalant to: 6 feet 3 inches!
Your weight is equivalant to: 330.694 kilograms!

//Invalid height
Enter height (in inches): -55
Error! Invalid height!
Cannot compute info.

//Invalid weight
Enter height (in inches): 75
Enter weight (in pounds): -100
Error! Invalid weight!
Cannot compute info.
</code></pre>

<h2 id="multiple-exceptions">Multiple Exceptions</h2>
<blockquote>
<blockquote>
<p>But wait....there's more!...</p>
</blockquote>
</blockquote>
<p>Multiple handlers (i.e., catch expressions) can be chained; each one with a different parameter type. Only the handler whose argument type matches the type of the exception specified in the throw statement is executed.</p>
<pre><code class="cpp">Exception handling using multiple handlers:

...
try
{
  ...
  throw objectOfExceptionType1;
  ...
  throw objectOfExceptionType2;
  ...
  throw objectOfExceptionType3;
  ...
}
catch (excptType1 &amp; exceptObj1)
{
  //Handle type1
}
catch (excptType2 &amp; exceptObj2)
{
  //Handle type2
}
catch (...)
{
  //Default handler. Catches all other objects (e.g. type3)
}
...//Execution continues
</code></pre>

<p>One thing to note is that if exceptObj2 is a subclass of exceptObj1, then objectOfExceptionType2 will always be caught by the first catch exception. A <em><strong>common error</strong></em> is to place a catch block intended to handle exceptions of a base class before catch blocks intended to handle exceptions of a derived class, preventing the latter from ever executing.</p>
<p>Here's an example of using multiple handles. Note that exceptions can also be nested!</p>
<pre><code class="cpp">#include &lt;iostream&gt;
#include &lt;vector&gt;
#include &lt;stdexcept&gt;
using namespace std;

int main()
{
  vector&lt;int&gt; v(10);
  int input = 0;
  int secondInput = 0;
  int thirdInput = 0;

  try
  {
      //Try getting a positive number. If a negative number is entered,
      //it will throw an exception but still continue to the code after the catch
      try
      {
        cout &lt;&lt; &quot;Enter a positive number: &quot;;
        cin &gt;&gt; input;

        if(input &lt; 0)
        {
          throw logic_error(&quot;input variable is invalid!&quot;);
        }
      }
      catch (logic_error &amp; excpt)
      {
          cout &lt;&lt; &quot;Logic error!: &quot; &lt;&lt; excpt.what() &lt;&lt; endl;
      }

      //Get negative number from user
      cout &lt;&lt; &quot;Enter a negative number: &quot;;
      cin &gt;&gt; secondInput;

      if(secondInput &gt; 0)
      {
        throw runtime_error(&quot;Second input is not a negative number!&quot;);
      }

      //Get 0 from user
      cout &lt;&lt; &quot;Enter 0: &quot;;
      cin &gt;&gt; thirdInput;

      if(thirdInput != 0)
      {
        throw -1;
      }

      //Attempt to access an out-of-range index
      cout &lt;&lt; v.at(20) &lt;&lt; endl; //This will throw an out-of-range exception

  }
  catch (out_of_range &amp; excpt)
  {
      cout &lt;&lt; &quot;Out of range error!: &quot; &lt;&lt; excpt.what() &lt;&lt; endl;
  }
  catch (runtime_error &amp; excpt)
  {
      cout &lt;&lt; &quot;Runtime error!: &quot; &lt;&lt; excpt.what() &lt;&lt; endl;
  }
  catch (...)
  {
      cout &lt;&lt; &quot;Non-zero error!: User did not input a 0!&quot; &lt;&lt; endl;
  }

  return 0;
}
</code></pre>

<pre><code class="cpp">Output:
//Valid inputs
Enter a positive number: 1
Enter a negative number: -1
Enter 0: 0
Out of range error!: vector::_M_range_check

//Invalid first input
Enter a positive number: -1
Logic error!: input variable is invalid!    //&lt;---- Note that the program still continues
Enter a negative number: -1
Enter 0: 0
Out of range error!: vector::_M_range_check

//Invalid second input
Enter a positive number: 1
Enter a negative number: 1
Runtime error!: Second input is not a negative number!

//Invalid third input
Enter a positive number: 1
Enter a negative number: -1
Enter 0: 9999
Non-zero error!: User did not input a 0!
</code></pre>
              
            </div>
          </div>
          <footer>
  
    <div class="rst-footer-buttons" role="navigation" aria-label="footer navigation">
      
        <a href="../lec_week_03_pt3/" class="btn btn-neutral float-right" title="Templates">Next <span class="icon icon-circle-arrow-right"></span></a>
      
      
        <a href="../lec_week_03/" class="btn btn-neutral" title="Stacks & Queues"><span class="icon icon-circle-arrow-left"></span> Previous</a>
      
    </div>
  

  <hr/>

  <div role="contentinfo">
    <!-- Copyright etc -->
    
  </div>

  Built with <a href="http://www.mkdocs.org">MkDocs</a> using a <a href="https://github.com/snide/sphinx_rtd_theme">theme</a> provided by <a href="https://readthedocs.org">Read the Docs</a>.
</footer>
	  
        </div>
      </div>

    </section>

  </div>

<div class="rst-versions" role="note" style="cursor: pointer">
    <span class="rst-current-version" data-toggle="rst-current-version">
      
      
        <span><a href="../lec_week_03/" style="color: #fcfcfc;">&laquo; Previous</a></span>
      
      
        <span style="margin-left: 15px"><a href="../lec_week_03_pt3/" style="color: #fcfcfc">Next &raquo;</a></span>
      
    </span>
</div>

</body>
</html>
